# Podfile

use_frameworks!

def testing_pods
    pod 'Quick'
    pod 'Nimble'
end

def dev_pods
    pod 'Alamofire', '~> 4.5'
end

target 'TDDExample' do 
    dev_pods
end

target 'TDDExampleTestsQuick' do
    testing_pods
end